steps:
  # Build the container image
  - name: 'eclipse-temurin:17-jdk-alpine'
    entrypoint: 'sh'
    args: [ '-c', './gradlew clean gnagCheck bootBuildImage -Partifactory_user=$$ARTIFACTORY_USER -Partifactory_password=$$ARTIFACTORY_PASSWORD -PimageTag=$COMMIT_SHA' ]
    secretEnv: ['ARTIFACTORY_USER', 'ARTIFACTORY_PASSWORD']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gnag-website:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'gnag-website', '--image', 'gcr.io/$PROJECT_ID/gnag-website:$COMMIT_SHA', '--region', 'us-central1' ]
availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_NUMBER/secrets/ARTIFACTORY_USER/versions/latest'
      env: 'ARTIFACTORY_USER'
    - versionName: 'projects/$PROJECT_NUMBER/secrets/ARTIFACTORY_PASSWORD/versions/latest'
      env: 'ARTIFACTORY_PASSWORD'
images:
  - 'gcr.io/$PROJECT_ID/gnag-website:$COMMIT_SHA'