spring.thymeleaf.cache: false

github:
  redirectUrl: http://127.0.0.1:8080/callback

logging:
  enabled: true
  exclude:
    - /actuator/health
  pattern:
    console: "%clr(%-5p) %clr([%8.20t]){cyan} %clr(%-10.35logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"